# Generated by Django 4.2.9 on 2024-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
    ]
